### ISSUE TITLE
Interface to certbot 2.0.0 seems to fail due to API changes

### ISSUE THREAD

**Issue by noci2012** [siilike/certbot-dns-standalone#18]
This is the resulting stack trace.
```
2022-11-25 18:31:48,615:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==2.0.0', 'console_scripts', 'certbot')())
  File "/usr/lib/python3.10/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1707, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.10/site-packages/certbot/_internal/plugins/disco.py", line 208, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/plugins/disco.py", line 215, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/plugins/disco.py", line 56, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.10/site-packages/certbot_dns_standalone/dns_standalone.py", line 21, in <module>
    @zope.interface.implementer(interfaces.IAuthenticator)
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
2022-11-25 18:31:48,615:ERROR:certbot._internal.log:An unexpected error occurred:
2022-11-25 18:31:48,615:ERROR:certbot._internal.log:AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
```
I haven't done any further investigation yet.

**Comment by Huitsi** [comment]
Certbot 2.0.0 removed zope interfaces. Removing the few lines referring to them ([as done in Certbot](https://github.com/certbot/certbot/commit/979e21dcbf11665f7839628cfae62e28fd2683df)) might be enough to fix this.

**Comment by siilike** [comment]
Should be fixed in v1.1.

**Comment by Huitsi** [comment]
Hmm, it looks like you pushed the tag but not the master branch.

**Comment by siilike** [comment]
Yes, now it should be available.

**Comment by noci2012** [comment]
And working.

**Comment by noci2012** [comment]
Gentoo ebuild:

```
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=7
PYTHON_COMPAT=(python{3_9,3_10,3_11})

if [[ ${PV} == 9999* ]]; then
        EGIT_REPO_URI="https://github.com/siilike/certbot-dns-standalone.git"
        EGIT_REPO_BRANCH="master"
        KEYWORDS="~amd64 ~arm ~arm64 ~x86"
        inherit git-r3
        S=${WORKDIR}/${P}
else
        SRC_URI="https://github.com/siilike/${PN}/archive/${PV}.tar.gz -> ${PN}-${PV}.tar.gz"
        KEYWORDS="~amd64 ~arm ~arm64 ~x86"
        S=${WORKDIR}/${P}
fi

inherit distutils-r1

DESCRIPTION="Standalone DNS plugin for certbot (Let's Encrypt Client)"
HOMEPAGE="https://github.com/certbot/certbot https://letsencrypt.org/ https://github.com/siilike/${PN}"

LICENSE="Apache-2.0"
SLOT="0"
IUSE=""

CDEPEND=">=dev-python/setuptools-1.0[${PYTHON_USEDEP}]"
RDEPEND="${CDEPEND}
        >=app-crypt/certbot-2.10[${PYTHON_USEDEP}]
        >=app-crypt/acme-0.40[${PYTHON_USEDEP}]
        >=dev-python/dnslib-0.9.0[${PYTHON_USEDEP}]"
DEPEND="${CDEPEND}"
```

**Comment by noci2012** [comment]
Thanks for fixing. for me it can be closed.
